{% set name = "dart-sass" %}
{% set version = "1.94.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/sass/dart-sass/archive/refs/tags/{{ version }}.tar.gz  # [not osx or not arm64]
    sha256: f0d8009cc5447b2f456781642e5e93b656f3badf87a406644206fa6a9b5fac80  # [not osx or not arm64]
  # binary repack for osx-arm64 due to compiling issues
  - url: https://github.com/sass/dart-sass/releases/download/{{ version }}/dart-sass-{{ version }}-macos-arm64.tar.gz  # [osx and arm64]
    sha256: 7dfb0723b318d87251883f1b4b59d84eaa003a0f615f4a12a6c8215b1cba0428  # [osx and arm64]

build:
  number: 0
  binary_relocation: false
  # we don't have dart-sdk on ppc64le, so we can't build this.
  skip: true  # [ppc64le]

requirements:
  host:
    - dart-sdk       # [not arm64]

test:
  files:
    - test.sass
  commands:
    - sass test.sass output.css  # [unix]
    - call sass test.sass output.css  # [win]

about:
  home: https://sass-lang.com/dart-sass
  dev_url: https://github.com/sass/dart-sass/
  doc_url: https://sass-lang.com/dart-sass
  license: MIT
  license_file:
    - LICENSE           # [not arm64]
    - src/LICENSE       # [osx and arm64]
  summary: Dart implementation of Sass. Sass makes CSS fun again.

extra:
  recipe-maintainers:
    - msarahan
