{% set name = "dart-sass" %}
{% set version = "1.32.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/sass/dart-sass/archive/refs/tags/{{ version }}.tar.gz
    sha256: 1b7679f55bd621af878265ce8b07e3de404779b5f390b6f74ef76c9bacf292b2

build:
  number: 0
  binary_relocation: False
  # we don't have dart-sdk on ppc64le, so we can't build this.
  skip: True   # [ppc64le]

requirements:
  host:
    - dart-sdk       # [not arm64]

test:
  files:
    - test.sass
  commands:
    - sass test.sass output.css

about:
  home: https://sass-lang.com/dart-sass
  license: MIT
  license_file:
    - LICENSE
  summary: Dart implementation of Sass. Sass makes CSS fun again.

extra:
  recipe-maintainers:
    - msarahan
