{% set name = "dart-sass" %}
{% set version = "1.54.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sass/dart-sass/archive/refs/tags/{{ version }}.tar.gz
  sha256: fbfe1590ef63998b62d108b2dd848ea71456e910c50405b0ae7fadc43212472b

build:
  number: 0
  binary_relocation: false
  missing_dso_whitelist:
    # normal linux stuff that would go away if we had libgcc-ng in the run deps
    - '*/ld-linux.so.2'
    - '*/lib64/ld-linux-x86-64.so.2'
    - '*/libpthread.so.0'
    - '*/libdl.so.2'
    - '*/libm.so.6'
    - '*/libc.so.6'

requirements:
  host:
    - dart-sdk   # [unix]
    - nodejs     # [win]
  run:
    - nodejs     # [win]

test:
  files:
    - test.sass
  commands:
    - sass test.sass output.css

about:
  home: https://sass-lang.com/dart-sass
  license: MIT
  license_file:
    - LICENSE
  summary: Dart implementation of Sass. Sass makes CSS fun again.

extra:
  recipe-maintainers:
    - msarahan
