context:
  version: "1.99.0"

package:
  name: dart-sass
  version: ${{ version }}

source:
  url: https://github.com/sass/dart-sass/archive/refs/tags/${{ version }}.tar.gz
  sha256: 5f969b2eedf86384d90a9a339824b6652a4600e9e5f32784a7e48e453e145016

build:
  number: 0
  dynamic_linking:
    binary_relocation: false
  skip:
    # we don't have dart-sdk on ppc64le, so we can't build this.
    - ppc64le

requirements:
  host:
    - dart-sdk
    - buf

tests:
  - script:
      - sass --version
      - sass test.sass
    files:
      recipe:
        - test.sass

about:
  homepage: https://sass-lang.com/dart-sass
  license: MIT
  license_file:
    - LICENSE
  summary: Dart implementation of Sass. Sass makes CSS fun again.
  documentation: https://sass-lang.com/dart-sass
  repository: https://github.com/sass/dart-sass

extra:
  recipe-maintainers:
    - msarahan
    - munechika-koyo
